Changed test workflow for windows
Changed the test workflow for windows because of
the following error:

Error: Unable to resolve action powershell/powershell-for-github-actions, repository not found

This is not required anymore as powershell core is always included when setting up windows.